# Generated by Django 3.1.6 on 2021-03-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.FloatField()),
                ('sgst', models.FloatField()),
            ],
            options={
                'verbose_name': 'GST',
                'verbose_name_plural': 'GST',
            },
        ),
        migrations.CreateModel(
            name='InvoicePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('dop', models.DateTimeField(auto_now_add=True, verbose_name='date of purchase')),
                ('status', models.BooleanField(verbose_name='Paid')),
                ('payment_mode', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('dos', models.DateTimeField(auto_now_add=True, verbose_name='date of selling')),
                ('status', models.BooleanField(verbose_name='Paid')),
            ],
            options={
                'verbose_name': 'Sell',
                'verbose_name_plural': 'Sells',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=450)),
                ('price', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.invoicesells')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.invoicepurchase')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=450, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.brand')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.itemcategory'),
        ),
        migrations.AddField(
            model_name='invoicesells',
            name='payment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.paymentmode'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_name', 'price', 'category')},
        ),
    ]
