# Generated by Django 3.1.6 on 2021-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesells',
            name='packing_chrg',
            field=models.FloatField(blank=True, null=True, verbose_name='Packing Charges'),
        ),
        migrations.AlterField(
            model_name='invoicesells',
            name='dos',
            field=models.DateTimeField(verbose_name='date of selling'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(default=60),
        ),
    ]
