# Generated by Django 3.1.6 on 2021-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210311_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesells',
            name='odr_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order Id'),
        ),
    ]
