# Generated by Django 3.1.6 on 2021-03-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_invoicesells_odr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesells',
            name='discount_note',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
