# Generated by Django 3.1.6 on 2021-02-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210209_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.item'),
        ),
    ]
