# Generated by Django 3.1.6 on 2021-02-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210210_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicepurchase',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='invoicesells',
            options={'verbose_name': 'Sell', 'verbose_name_plural': 'Sells'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='invoicepurchase',
            name='dop',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of purchase'),
        ),
        migrations.AlterField(
            model_name='invoicesells',
            name='dos',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of selling'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('item_name', 'price', 'category')},
        ),
    ]
