# Generated by Django 3.1.6 on 2021-03-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20210312_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesells',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Is Cancelled'),
        ),
    ]
