# Generated by Django 3.1.6 on 2021-02-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210211_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=450, unique=True),
        ),
    ]
