# Generated by Django 3.1.6 on 2021-03-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_invoicesells_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicesells',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='invoicesells',
            name='odr_id',
        ),
        migrations.AlterField(
            model_name='invoicesells',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Paid'),
        ),
    ]
