# Generated by Django 3.1.6 on 2021-03-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20210312_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesells',
            name='status',
            field=models.BooleanField(default=True, null=True, verbose_name='Paid'),
        ),
    ]
