# Generated by Django 3.1.6 on 2021-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20210312_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesells',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Paid'),
        ),
    ]
