# Generated by Django 3.1.6 on 2021-03-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20210312_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesells',
            name='dos',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date of selling'),
        ),
    ]
