# Generated by Django 3.1.6 on 2021-03-18 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20210318_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepurchase',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.paymentmode'),
        ),
    ]
