# Generated by Django 3.1.6 on 2021-03-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20210318_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepurchase',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
