# Generated by Django 3.1.6 on 2021-03-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_invoicepurchase_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.invoicepurchase'),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.invoicesells'),
        ),
    ]
